### ISSUE TITLE
uninitialized constant Mongoid::Token error upon installation

### ISSUE THREAD

**Issue by omidify** [thetron/mongoid_token#16]
Upon following installation instructions, I got an uninitialized constant Mongoid::Token error.  

Token declaration was for my user model:

```
class User
  include Mongoid::Document
  include Mongoid::Timestamps  
  include Mongoid::Token

  FIELDS HERE

  token :length => 6
```

Rails version 3.2.9, Ruby 1.9.3v327 on x86_64_darwin11.4.2, Mongoid 3.0.14, 3.0.13 and Mongoid_token 1.1.0

**Comment by irfanfadilah** [comment]
I got `NameError: uninitialized constant Mongoid::Token::Collisions::Moped` out of nowhere, it's happened when I tried to create new object..

Tried your suggestion to run the rake command and resave the model but the error still persist..
