### ISSUE TITLE
'find' doesn't work with associations

### ISSUE THREAD

**Issue by saharaying** [thetron/mongoid_token#32]
for example: `form.entries.find token` will query by _id instead of token

**Comment by thetron** [comment]
I was able to confirm this issue with a new spec in #52 - however the more I explored it, the uglier it got. I'm going to deprecate the monkey-patched finders and explore the idea of (optionally) replacing the default mongoid `_id` field with the token (#8), negating the need for the monkey-patched finders.

Thank you both for your feedback! :beers: :cake:
