### ISSUE TITLE
undefined method `args' in token.rb

### ISSUE THREAD

**Issue by warmwind** [thetron/mongoid_token#50]
The method below in ```token.rb``` call super with param ```*args```. However, the args does not exist. In previous version it is inside ```token(*args)``` method. 

It seems a mistake after extracting it as a method out of ```token(*args)``` method.

```ruby
private
def override_to_param(options)
   self.send(:define_method, :to_param) do
     self.send(options.field_name) || super(*args)
   end
end
```

**Comment by thetron** [comment]
@warmwind I was looking over the open issues here, and I think this fix of yours was merged in a while ago - so I'm going to close this. Thanks again for your help! :smile:
