### ISSUE TITLE
Am I using mongoid_token incorrectly? or is this a bug?

### ISSUE THREAD

**Issue by Igneous** [thetron/mongoid_token#52]
If I create an object and some embedded children at once, _then_ call .save on it, it seems like only the root object gets a token, and the embedded ones don't ever get tokens generated for them.

Here's a gist of what I'm doing:
https://gist.github.com/anonymous/45942d8f240da1288852

**Comment by thetron** [comment]
Sorry for the delay on this one @Igneous  - I was able to replicate your issue, and have added a failing test case. I know it's probably too late you help you on whatever you were working on at the time - but I'm going to see about getting this patched ASAP.

**Comment by thetron** [comment]
@Igneous After exploring this for a while, I think it's confirmed my long-held suspicion that monkey-patching `find` is a pretty horrible way to handle things.

In the next big release of this gem, I plan on exploring adding support for using the token as the `_id` field, which would negate the need for the monkey patched finders (Here: #8). I'll close this issue for now,  as I think the solution is to use the `find_by_*` query methods, which was your solution.

Thanks heaps again for all your feedback. :cake:
