### ISSUE TITLE
Rails Admin has_many relations fail to save

### ISSUE THREAD

**Issue by artmees** [thetron/mongoid_token#53]
I have the following 2 models

```rb
class Student < User
  token pattern: "S_%d8"
  belongs_to :parent
end

class Parent < User
  token pattern: "P_%d8"
  has_many :students
end
```

on Rails_admin Parent Page when I try to save the Parent without any changes I get the following error
```
Problem: Document not found for class Student with attributes {:token=>[]}.
Summary: When calling Student.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.
```
the same problem also exists when I try to add any student to the parent class via Rails admin...
```
Problem: Document not found for class Student with attributes {:token=>[BSON::ObjectId('54528faf416264e024000000')]}.
Summary: When calling Student.find_by with a hash of attributes, all attributes provided must match a document in the database or this error will be raised.
```

**One Important thing to note** is when I add `skip_finders: true` to `Student` model every thing works as expected (but without the mongoid_token support for `Student`s of course)

**Comment by thetron** [comment]
@artmees I didn't get anything further from you on this issue, so I'm going to assume it was elsewhere, but feel free to comment if you're still having issues (I hope not, after 8 months! :smile:).
