### ISSUE TITLE
Can i use token as foreign key?

### ISSUE THREAD

**Issue by calfzhou** [thetron/mongoid_token#59]
Thanks for this great tool for generating tokens!

Now i have a relation between two collections, for example a company `has_many` staffs, and a staff `belongs_to` a company. I'v already add tokens to each model, but when I created a new staff for a company, the foreign key is still using company's object id (`_id` field), how can i use company's `token` field as the foreign key?

**Comment by calfzhou** [comment]
If the default foreign key cannot be changed, how can i add a new field to staff to store its company's token? I need this token because when i return a staff's data to API caller, I don't want to use another query to look up company's token.

**Comment by thetron** [comment]
First of all, my apologies for the delay getting back to you @calfzhou. I'm sure you have this sorted by now, but I figured I would follow up anyway.

There's currently another feature request (#8) which would add support for replacing the default `_id` field in Mongoid with the token, but I've yet to explore that any further, and would likely not appear until the we add support for Mongoid 5.

That being said, this could be achieved in a few ways, by adding a field to your `Staff` model for `company_token`, and caching that value when a member of staff is added to a company.

Alternatively - and arguably more easy - would be to eager-load (See 'Eager Loading' [here](http://mongoid.org/en/mongoid/docs/querying.html#queries)) the company when you load a staff member in the API. Then you'll avoid the N+1 problem, and you don't need to worry about data integrity.

Thanks for your feedback! :cake: :smile:

**Comment by thetron** [comment]
Sorry - I closed the issue, but feel free to discuss if you have any further questions :smile:

**Comment by calfzhou** [comment]
Thanks @thetron for the feedback! We are just using _id as foreign key now.
