### ISSUE TITLE
Readme should say `bundle install` not `bundle update`

### ISSUE THREAD

**Issue by hooverlunch** [thetron/mongoid_token#60]
Should they not? I thought updating your entire bundle for the sake of one gem was a bad idea...

Great gem!

PS. The gem version should not be pegged at 2.0.0. That's an old release. ~> 2.0 worked for me.

**Comment by thetron** [comment]
@hooverlunch you are totally right!! Thanks for catching that - it's been a while since i've looked at the readme in any detail.
