### ISSUE TITLE
Cannot ensure unique token on embeded documents

### ISSUE THREAD

**Issue by calfzhou** [thetron/mongoid_token#63]
I just found that Mongoid currently cannot enforce unique index within of single document (for example a `embeds_many` relationship).

I'm using `embeds_many` and set a token to the embeded document:

```ruby
token field_name: :token, length: 1, contains: :fixed_numeric_no_leading_zeros
```

Then I generate a lot of embeded documents (more than 10), all of them can be saved successfully, and their tokens have duplications.

**Comment by thetron** [comment]
Unless something has changed with MongoDB, I believe this is a limitation at the database level. Believe you can enforce the index from the parent document - but this will apply across the parent's collection with something like:

```ruby
class Foo
  include Mongoid::Document
  embeds_many :bars

  index "bars.token", unique: true
end

class Bar
  include Mongoid::Document
  include Mongoid::Token
  embedded_in :foo
  token
end
```

But, again - this is enforced across the Foo collection, so you'd need to take that into consideration when choosing the structure for your tokens.

**Comment by calfzhou** [comment]
Thanks, this is a bug in mongodb, and there is no way to define a proper unique index for this scenario. Please feel free to close this issue.

**Comment by thetron** [comment]
Thanks - yeah it's pretty frustrating.

Previously we were leveraging Rails validations to enforce uniqueness, and whilst it handled this case it was substantially slower - and I think maybe even subject to race conditions (at least at the time).
